# Your workflow name.
name: Deploy to Render

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Your workflow jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      ### ⬇ IMPORTANT PART ⬇ ###
      - name: Deploy to Render
        uses: render/webhooks@v1
        with:
          render_account_id: ${{ secrets.cn7i2kmct0pc738uqs60}}
          render_token: ${{ secrets.rnd_bGOd3J71DHIR8fE2sZBSavz3Cvhd}}
          render_yaml_path: ./main.yaml # Path to your Render YAML configuration file
      ### ⬆ IMPORTANT PART ⬆ ###
